name: red_tail
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: 4.6.5
  animated_text_kit: ^4.2.2
  #video_thumbnail: ^0.5.3
  #video_player: ^0.10.11+1
  orientation: ^1.2.0
  dropdown_button2: ^1.9.2
  zoom_tap_animation: ^1.1.0
  font_awesome_flutter: ^10.3.0
  cached_network_image: ^3.2.3
  google_maps_flutter: ^2.2.3
  floor: ^1.4.1
  chewie: ^1.4.0
  carousel_slider: ^4.2.1
  video_player: ^2.5.1
  # lottie: ^2.2.0
  location: ^4.4.0
  intl: ^0.18.0
  cool_alert: ^1.1.0
  connectivity_plus: ^3.0.3
  dio: ^4.0.6
  package_info_plus: ^3.0.3
  get_storage: ^2.0.3
  mime: ^1.0.4
  workmanager: ^0.5.1
  fluttertoast: ^8.1.3
  flutter_spinkit: ^5.1.0
  # shared_preferences: ^2.0.17
  # flutter_background: ^1.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.11.0

  # flutter_lints: ^2.0.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/remark.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/remark.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/remark.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/remark.png"
flutter:
  assets:
    - assets/logo/
    - assets/images/

  uses-material-design: true
