name: red_tail
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: 4.6.5
  animated_text_kit: ^4.2.2
  #video_thumbnail: ^0.5.3
  fluttertoast: ^8.0.9
  #video_player: ^0.10.11+1
  orientation: ^1.2.0
  dropdown_button2: ^1.9.2
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # flutter_lints: ^2.0.0
  

flutter:
  assets:
    - assets/logo/
    - assets/images/

  uses-material-design: true
